/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projettictactoe;

import java.io.FileInputStream;
import java.io.ObjectInputStream;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author elham
 */
public class ProjectsDialog extends javax.swing.JDialog {
    
     private String user;
     private DefaultTableModel mode = null;
     private static final String gamesFolder = "./games/";
     private List<int[]> etapes = new ArrayList<>();
     private HashMap<String,String> specifications = new HashMap<>(); 
     private HashMap<Integer, TictactoePanel> panels = new HashMap<>();
     private int depth;
     
    public ProjectsDialog(java.awt.Frame parent, boolean modal,String user) {
        super(parent, modal);
        initComponents();
        this.user=user;
         mode = (DefaultTableModel) jTable1.getModel();
        List<String> games = this.getAllGames();
        System.out.println(games);
        for (int i = 0; i < games.size(); i=i+2) {
                 
             mode.addRow(new Object[]{games.get(i),games.get(i+1)});
                     
                      
                    
                }
    }
    public ProjectsDialog(java.awt.Frame parent, boolean modal){}
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        charger = new javax.swing.JButton();
        nvpartie = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "adversaire", "nomPartie"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        charger.setText("charger ");
        charger.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chargerActionPerformed(evt);
            }
        });

        nvpartie.setText("nouvelle partie");
        nvpartie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nvpartieActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(26, 26, 26)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 338, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(153, 153, 153)
                                .addComponent(charger))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(136, 136, 136)
                                .addComponent(nvpartie)))
                        .addGap(0, 28, Short.MAX_VALUE))
                    .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(charger)
                .addGap(28, 28, 28)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addComponent(nvpartie)
                .addGap(64, 64, 64))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void chargerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chargerActionPerformed
        int i=jTable1.getSelectedRow();
        
        String adv = (String) jTable1.getValueAt(i,1);
        System.out.println(adv);
        try {
             FileInputStream file = new FileInputStream(gamesFolder+adv);
          ObjectInputStream ab = new ObjectInputStream(file);
          depth = (int)ab.readInt();
          etapes = (List<int[]>)ab.readObject();
          specifications = (HashMap<String,String>)ab.readObject();
            System.out.println("depth: "+depth);
          
          Vector<int[]> t = (Vector<int[]>)ab.readObject();
         Principale p = new Principale(adv,etapes,specifications,t,depth);
         p.setVisible(true);
         p.setLocationRelativeTo(null);
         this.dispose();
            
        } catch (Exception e) {
        }
    }//GEN-LAST:event_chargerActionPerformed

    private void nvpartieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nvpartieActionPerformed
        StartDialog d = new StartDialog(null,false,user );
        d.setVisible(true);
        d.setLocationRelativeTo(null);
        
        this.dispose();
    }//GEN-LAST:event_nvpartieActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jTable1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ProjectsDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ProjectsDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ProjectsDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ProjectsDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ProjectsDialog dialog = new ProjectsDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
public List<String> getAllGames (){
    List<String> games = new ArrayList<>();
       try {
            Class.forName("com.mysql.jdbc.Driver").newInstance();
             Connection cnx = DriverManager.getConnection("jdbc:mysql://localhost/tictactoe", "root", "");
            PreparedStatement sel = cnx.prepareStatement("select * from partie where user = ?");
            sel.setString(1, this.user);
            ResultSet tt = sel.executeQuery();
             while (tt.next()) {
                String tets1 = tt.getString("nomadv");
                String tets2 = tt.getString("nomfichier");
                games.add(tets1);
               games.add(tets2);
      
            }
        } catch (Exception ex) {
            Logger.getLogger(Sign.class.getName()).log(Level.SEVERE, null, ex);
        }
    return games;
}
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton charger;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton nvpartie;
    // End of variables declaration//GEN-END:variables
}
