/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projettictactoe;

import java.awt.Color;
import java.awt.Component;
import java.awt.GridLayout;
import java.io.Serializable;
import java.util.HashMap;
import java.util.List;

/**
 *
 * @author elham
 */
public class TictactoePanel extends javax.swing.JPanel implements Serializable{

    /**
     * Creates new form TictactoePanel
     */
     private HashMap<Integer,Buttons> buttons = new HashMap<>();
     private Principale principale;
     private static int idPanel=0;
     public static int lastelement;
     private int idp;
     
    public TictactoePanel(Principale principale) {
        idp=idPanel;
        initComponents();
        this.principale = principale;
        this.setVisible(true);
        this.setSize(100, 100);
        //this.setBackground(Color.BLACK);
        this.setLayout(new GridLayout(3, 3));
        
        for(int i=0;i<9;i++){
            buttons.put(i, new Buttons(i,this.principale,idPanel));
            this.add(this.buttons.get(i));
        }
        idPanel++;
        this.idp=idPanel;
    }
    public TictactoePanel(Principale principale,List<int[]> etapes,HashMap<String,String> specifications) {
        initComponents();
        this.principale = principale;
        this.setVisible(true);
        this.setSize(100, 100);
        //this.setBackground(Color.BLACK);
        this.setLayout(new GridLayout(3, 3));
        List<int[]> etape = etapes;
        
        for(int i=0;i<9;i++){
            buttons.put(i, new Buttons(i,this.principale,idPanel));
            this.add(this.buttons.get(i));
        }
        
        if (!etape.isEmpty()) {
            for (int i = 0; i < etape.size(); i++) {
            int[] get = etape.get(i);
            if (get[0]==idPanel) {
                
                buttons.get(get[1]).setXo(get[2]);
                buttons.get(get[1]).setEtat(false);
                if (get[2]==1) {
                    buttons.get(get[1]).setText("<html><font color = blue>X</font></html>");
                }
                if (get[2]==-1) {
                    buttons.get(get[1]).setText("<html><font color = red>O</font></html>");
                }
                
            }
        }
            if (etape.get(etape.size()-1)[2]== 1) {
            Buttons.tour=false;
            lastelement=etape.get(etape.size()-1)[1];
            
        }
        if (etape.get(etape.size()-1)[2]== -1) {
            Buttons.tour=true;
            lastelement=etape.get(etape.size()-1)[1];
        }
        }
        
//        for (int i = 0; i < etape.size(); i++) {
//            int[] get = etape.get(i);
//        }
        
        this.idp=idPanel;
        idPanel++;
        
    }
    
//       public TictactoePanel(Principale principale,List<int[]> etapes) {
//        initComponents();
//        this.principale = principale;
//        this.setVisible(true);
//        this.setSize(100, 100);
//        //this.setBackground(Color.BLACK);
//        this.setLayout(new GridLayout(3, 3));
//        
//        for(int i=0;i<9;i++){
//            buttons.put(i, new Buttons(i,this.principale,idPanel));
//            this.add(this.buttons.get(i));
//        }
//        idPanel++;
//    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    public HashMap<Integer, Buttons> getButtons() {
        return buttons;
    }

    public void setButtons(HashMap<Integer, Buttons> buttons) {
        this.buttons = buttons;
    }

    public int getIdp() {
        return idp;
    }

    public void setIdp(int idp) {
        this.idp = idp;
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables


   


}
